baseurl = "https://thenewbestpractices.com"
languageCode = "en-us"
title = "The New Best Practices"
theme = "castanet"
googleAnalytics = "UA-4184025-14"
disqusShortname = "the-new-best-practices"

[permalinks]
  about = "/:filename/"
  episode = "/:filename/"

[[Menu.Main]]
  name = "About"
  identifier = "about"
  url = "about"

[params]
  site_theme = "blue"
  site_layout = "row"
  enable_jumbo = "true"
  custom_css = ["custom.css"]
  # truncate = "100"
  about_logo = "/images/new.png"
  copyright_notice = "Copyright 2017 [Ross Hunter](https://ross-hunter.com)"
  itunes_subscribe = "https://itunes.apple.com/us/podcast/the-new-best-practices/id1338992148?mt=2"
  # android_subscribe = ""
  google_play_subscribe = "https://playmusic.app.goo.gl/?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&apn=com.google.android.music&link=https://play.google.com/music/m/I3v4jyrk7ys55cryycm5rtoopsq?t%3DThe_New_Best_Practices%26pcampaignid%3DMKT-na-all-co-pr-mu-pod-16"
  stitcher_subscribe = "https://www.stitcher.com/s?fid=165804&refid=stpr"
  # soundcloud_subscribe = ""
  # mailchimp_subscribe = ""
  #rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
  description = "The New Best Practices is a podcast about the process of creating software."
  media_prefix = "https://thenewbestpractices.com"
  [params.feed]
    feed_copyright = "Copyright 2017 Ross Hunter"
    itunes_subtitle = "Really Good Podcast"
    itunes_author = "Ross Hunter"
    itunes_summary = "The New Best Practices is a podcast about the process of creating software."
    itunes_owner_name = "Ross Hunter"
    itunes_owner_email = "ross-hunter@ross-hunter.com"
    itunes_image = "https://thenewbestpractices.com/images/new.png"
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Software How-To"
    itunes_second_sub_category = "Tech News"

  [params.social]
    facebook = "thenewbestpractices"
    facebook_admin = "208701582"
    twitter = "newbestpractice"

  [params.authors]
    [params.authors.Ross]
      identifier = "1"
      name  = "Ross Hunter"
      thumbnail = "/images/ross.png"
      bio = "Ross is a Rubyist at heart, he values his own happiness and productivity above being one of the cool kids. He actively works on not being an overly-cynical curmudgeon &mdash; he does not do a good job. "
      [params.authors.Ross.social]
        github = "Ross-Hunter"
        facebook = "ross.hunter"
        twitter = "ross-hunter"
        linkedin = "rosshunter"
        homepage = "https://ross-hunter.com"
    [params.authors.Jason]
      identifier = "2"
      name = "Jason Sich"
      thumbnail = "/images/jason.jpeg"
      bio = "Jason is a journeyman searching for both the objective & subjective truths of software development. He is never content and always restless."
      [params.authors.Jason.social]
        twitter = "jasich"
        github = "jasich"
        linkedin = "jasich"
    [params.authors.Jace]
      identifier = "3"
      name = "Jace Browning"
      thumbnail = "/images/jace.jpg"
      bio = "Jace Browning builds, customizes, integrates, and teaches engineering software tools. He has worked on products in the embedded, mobile, and web space, but his expertise is systems programming, specifically in Python. Professionally, he focuses on quality assurance, automation, and process optimization. In his free time, he enjoys contributing to open source and volunteering at local technology events."
      [params.authors.Jace.social]
        twitter = "jacebrowning"
        github = "jacebrowning"
        linkedin = "jacebrowning"
        homepage = "http://jacebrowning.info"

    [params.links]
      [params.links.ross]
        name = "Ross-Hunter"
        url = "https://ross-hunter.com.com"
