baseurl = "http://thenewbestpractices.com"
languageCode = "en-us"
title = "The New Best Practices"
theme = "castanet"
googleAnalytics = "UA-4184025-14"
disqusShortname = "the-new-best-practices"

[permalinks]
  about = "/:filename/"
  episode = "/:filename/"

[[Menu.Main]]
  name = "About"
  identifier = "about"
  url = "about"

[params]
  site_theme = "blue"
  site_layout = "row"
  enable_jumbo = "true"
  custom_css = ["custom.css"]
  # truncate = "100"
  # about_logo = "/img/hugocast.png"
  copyright_notice = "Copyright 2017 [Ross Hunter](https://ross-hunter.com)"
  itunes_subscribe = ""
  android_subscribe = ""
  google_play_subscribe = ""
  sticher_subscribe = ""
  soundcloud_subscribe = ""
  mailchimp_subscribe = ""
  #rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
  description = "The New Best Practices is a podcast about creating software. We publish our podcast in \"seasons\" that we release whenever we feel it's ready. Season 1 is available now."
  media_prefix = ""
  [params.feed]
    feed_copyright = "Copyright 2017 Ross Hunter"
    itunes_subtitle = "Really Good Podcast"
    itunes_author = "Ross Hunter"
    itunes_summary = "Really Good Podcast"
    itunes_owner_name = "Ross Hunter"
    itunes_owner_email = "ross-hunter@ross-hunter.com"
    itunes_image = ""
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Software How-To"
    itunes_second_sub_category = "Tech News"

  [params.social]
    facebook = "thenewbestpractices"
    facebook_admin = "208701582"
    twitter = "newbestpractice"

  [params.authors]
    [params.authors.Ross]
      identifier = "1"
      name  = "Ross Hunter"
      thumbnail = "/images/ross.png"
      bio = "Ross Hunter is a pretty cool web dude."
      [params.authors.Ross.social]
        github = "Ross-Hunter"
        facebook = "ross.hunter"
        twitter = "ross-hunter"
        linkedin = "rosshunter"
        homepage = "https://ross-hunter.com"
    [params.authors.Jason]
      identifier = "2"
      name = "Jason Sich"
      thumbnail = "/images/jason.jpeg"
      bio = "Jason Sich is best known as author of the Sich New Technical Dictionary."
      [params.authors.Jason.social]
        twitter = "jasich"
    [params.authors.Jace]
      identifier = "3"
      name = "Jace Browning"
      thumbnail = "/images/jace.jpg"
      bio = "Jace Browning likes to complain about software."
      [params.authors.Jace.social]
        twitter = "jacebrowning"

    [params.links]
      [params.links.ross]
        name = "Ross-Hunter"
        url = "https://ross-hunter.com.com"
